# Generated by Django 4.2 on 2023-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('nominations', models.CharField(choices=[('n1', 'Самый стильный преподаватель'), ('n2', 'Самый инновационный преподаватель'), ('n3', 'Лучший лектор'), ('n4', 'Душа компании'), ('n5', 'Активист года'), ('n6', 'Самый изобретательный'), ('n7', 'Спортсмен года'), ('n8', 'Самый творческий'), ('n9', 'ПОЛИТЕХНИК ГОДА'), ('n10', 'ПРЕПОДАВАТЕЛЯ ГОДА'), ('n11', 'Мероприятие года')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография')),
                ('id_condidate', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
