# Generated by Django 4.2 on 2023-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='')),
                ('nomination', models.CharField(max_length=255)),
                ('id_condidate', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
