# Generated by Django 4.2 on 2023-10-22 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStudent',
            fields=[
                ('nominations', models.CharField(choices=[('Активист года', 'Активист года'), ('Спортсмен года', 'Спортсмен года'), ('Изобретатель года', 'Изобретатель года'), ('Политехник года', 'Политехник года'), ('Видео', 'Видео'), ('Дизайн', 'Дизайн'), ('Фото', 'Фото')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Students/')),
                ('institute', models.CharField(max_length=25)),
                ('group', models.CharField(max_length=25)),
                ('about', models.TextField()),
                ('id_S', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='N_ns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Самый стильный преподаватель', 'Самый стильный преподаватель'), ('Самый прогрессивный преподаватель', 'Самый прогрессивный преподаватель'), ('Лучший лектор', 'Лучший лектор'), ('Лучший наставник', 'Лучший наставник'), ('Преподаватель года', 'Преподаватель года'), ('Активист года', 'Активист года'), ('Спортсмен года', 'Спортсмен года'), ('Изобретатель года', 'Изобретатель года'), ('Политехник года', 'Политехник года'), ('Видео', 'Видео'), ('Дизайн', 'Дизайн'), ('Фото', 'Фото')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateTeacher',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Teachers/', verbose_name='Фотография')),
                ('department', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('about', models.TextField()),
                ('id_T', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_ns')),
            ],
        ),
    ]
