# Generated by Django 4.2 on 2023-10-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestudent',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_ns'),
        ),
    ]
