# Generated by Django 4.2 on 2023-10-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidatestudent_nominations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestudent',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominationss', to='voting.n_ns'),
        ),
        migrations.AlterField(
            model_name='candidateteacher',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominationst', to='voting.n_ns'),
        ),
        migrations.AlterModelTable(
            name='candidatestudent',
            table='Студенты',
        ),
        migrations.AlterModelTable(
            name='candidateteacher',
            table='Преподаватели',
        ),
        migrations.AlterModelTable(
            name='n_ns',
            table='Номинации',
        ),
    ]
