# Generated by Django 4.2 on 2023-10-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_candidatestudent_nominations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateteacher',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='voting.n_ns'),
        ),
    ]
