# Generated by Django 4.2 on 2023-10-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_candidateteacher_nominations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestudent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidateteacher',
            name='name',
        ),
        migrations.AddField(
            model_name='candidatestudent',
            name='first_name',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AddField(
            model_name='candidatestudent',
            name='second_name',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateteacher',
            name='first_name',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateteacher',
            name='second_name',
            field=models.CharField(default='123', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidateteacher',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_ns'),
        ),
        migrations.AlterField(
            model_name='n_ns',
            name='name',
            field=models.CharField(choices=[('Самый стильный преподаватель', 'Самый стильный преподаватель'), ('Самый прогрессивный преподаватель', 'Самый прогрессивный преподаватель'), ('Лучший лектор', 'Лучший лектор'), ('Лучший наставник', 'Лучший наставник'), ('Преподаватель года', 'Преподаватель года'), ('Активист года', 'Активист года'), ('Спортсмен года', 'Спортсмен года'), ('Изобретатель года', 'Изобретатель года'), ('Политехник года', 'Политехник года'), ('Видео', 'Видео'), ('Дизайн', 'Дизайн'), ('Фото', 'Фото')], max_length=255, unique=True),
        ),
    ]
