# Generated by Django 4.2 on 2023-10-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_candidatestudent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestudent',
            name='id_S',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidateteacher',
            name='id_T',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='n_ns',
            name='name',
            field=models.CharField(choices=[('Самый стильный преподаватель', 'Самый стильный преподаватель'), ('Самый прогрессивный преподаватель', 'Самый прогрессивный преподаватель'), ('Лучший лектор', 'Лучший лектор'), ('Лучший наставник', 'Лучший наставник'), ('Преподаватель года', 'Преподаватель года')], max_length=255, unique=True),
        ),
    ]
