# Generated by Django 4.2 on 2023-10-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_candidatestudent_id_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateteacher',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='voting.n_ns'),
        ),
    ]
