# Generated by Django 4.2 on 2023-10-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_candidateteacher_nominations'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_nsS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Активист года', 'Активист года'), ('Спортсмен года', 'Спортсмен года'), ('Изобретатель года', 'Изобретатель года'), ('Политехник года', 'Политехник года'), ('Видео', 'Видео'), ('Дизайн', 'Дизайн'), ('Фото', 'Фото')], max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Номинации Студентов',
            },
        ),
        migrations.CreateModel(
            name='N_nsT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Самый стильный преподаватель', 'Самый стильный преподаватель'), ('Самый прогрессивный преподаватель', 'Самый прогрессивный преподаватель'), ('Лучший лектор', 'Лучший лектор'), ('Лучший наставник', 'Лучший наставник'), ('Преподаватель года', 'Преподаватель года')], max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Номинации Преподавателей',
            },
        ),
        migrations.AlterField(
            model_name='candidatestudent',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_nss'),
        ),
        migrations.AlterField(
            model_name='candidateteacher',
            name='nominations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_nst'),
        ),
        migrations.DeleteModel(
            name='N_ns',
        ),
    ]
