# Generated by Django 4.2 on 2023-10-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_n_nss_n_nst_alter_candidatestudent_nominations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n_nst',
            name='name',
            field=models.CharField(choices=[('Самый стильный', 'Самый стильный'), ('Самый прогрессивный', 'Самый прогрессивный'), ('Лучший лектор', 'Лучший лектор'), ('Лучший наставник', 'Лучший наставник'), ('Преподаватель года', 'Преподаватель года')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn1', to='voting.candidateteacher')),
                ('nomination10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn10', to='voting.candidatestudent')),
                ('nomination11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn11', to='voting.candidatestudent')),
                ('nomination12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn12', to='voting.candidatestudent')),
                ('nomination2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn2', to='voting.candidateteacher')),
                ('nomination3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn3', to='voting.candidateteacher')),
                ('nomination4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn4', to='voting.candidateteacher')),
                ('nomination5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn5', to='voting.candidateteacher')),
                ('nomination6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn6', to='voting.candidatestudent')),
                ('nomination7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn7', to='voting.candidatestudent')),
                ('nomination8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn8', to='voting.candidatestudent')),
                ('nomination9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vn9', to='voting.candidatestudent')),
            ],
        ),
    ]
