# Generated by Django 4.2 on 2023-10-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_n_nst_name_v'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='n_nss',
            table=None,
        ),
        migrations.AlterModelTable(
            name='n_nst',
            table=None,
        ),
    ]
