# Generated by Django 4.2 on 2023-10-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_n_nss_table_alter_n_nst_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestudent',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Students/'),
        ),
        migrations.AlterField(
            model_name='candidateteacher',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='Teachers/', verbose_name='Фотография'),
        ),
    ]
