# Generated by Django 4.2 on 2023-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_candidatestudent_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n_nst',
            name='name',
            field=models.CharField(choices=[('Самый стильный', 'Самый стильный'), ('Самый прогрессивный', 'Самый прогрессивный'), ('Лучший лектор', 'Лучший лектор'), ('Наставник года', 'Наставник года'), ('Преподаватель года', 'Преподаватель года')], max_length=255, unique=True),
        ),
    ]
