# Generated by Django 4.2 on 2023-11-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_alter_n_nst_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='N_nsE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Мероприятие года', 'Мероприятие года')], default='Мероприятие года', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='n_nss',
            name='name',
            field=models.CharField(choices=[('Активист года', 'Активист года'), ('Спортсмен года', 'Спортсмен года'), ('Изобретатель года', 'Изобретатель года'), ('Политехник года', 'Политехник года'), ('Техническое искусство. Видео', 'Техническое искусство. Видео'), ('Техническое искусство. Дизайн', 'Техническое искусство. Дизайн'), ('Техническое искусство. Фото', 'Техническое искусство. Фото')], max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('name', models.CharField(default='123', max_length=255)),
                ('first_name', models.CharField(default='123', max_length=255)),
                ('second_name', models.CharField(default='', max_length=1)),
                ('foto', models.ImageField(blank=True, default='default.jpg', upload_to='Event/', verbose_name='Фотография')),
                ('organizers', models.CharField(max_length=255)),
                ('id_E', models.AutoField(primary_key=True, serialize=False)),
                ('nominations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.n_nse')),
            ],
            options={
                'db_table': 'Мероприятия',
            },
        ),
        migrations.AddField(
            model_name='v',
            name='nomination13',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vn13', to='voting.candidateevent'),
            preserve_default=False,
        ),
    ]
