# Generated by Django 4.2 on 2023-11-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_n_nse_alter_n_nss_name_candidateevent_v_nomination13'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidateevent',
            name='second_name',
        ),
    ]
