# Generated by Django 4.2 on 2023-11-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_remove_candidateevent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateevent',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
