# Generated by Django 4.2 on 2023-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pepople',
            fields=[
                ('institute', models.CharField(choices=[('IRIT', 'ИРИТ'), ('INEU', 'ИНЭУ'), ('IFHTiM', 'ИФХТиМ'), ('INEL', 'ИНЭЛ'), ('IPTM', 'ИПТМ'), ('ITS', 'ИТС'), ('ITAEiTF', 'ИЯЭиТФ')], max_length=7)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('group', models.CharField(max_length=25)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
