# Generated by Django 4.2 on 2023-10-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pepople',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('flag', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
