# Generated by Django 4.2 on 2023-10-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pepople',
            old_name='name',
            new_name='username',
        ),
    ]
