# Generated by Django 4.2 on 2023-10-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_pepople_options_alter_pepople_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepople',
            name='flag',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
