# Generated by Django 4.2 on 2023-10-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_name_pepople_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepople',
            name='password',
        ),
    ]
