# Generated by Django 4.2 on 2023-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_pepople_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepople',
            name='password',
            field=models.CharField(default=12345678, max_length=15),
            preserve_default=False,
        ),
    ]
