# Generated by Django 4.2 on 2023-10-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_n_nst_name_v'),
        ('registration', '0003_alter_pepople_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepople',
            name='flag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.v'),
        ),
    ]
